name = "reminder"
type = "javascript"

account_id = ""
workers_dev = true
# route = ""
# zone_id = ""

compatibility_date = "2022-03-29"
compatibility_flags = []

[build]
command = "yarn run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
durable_objects_persist = true

# [secrets]
# MAILGUN_API_BASE_URL
# MAILGUN_API_KEY
